#!/bin/bash

while true; do
  inotifywait -qqe unmount,modify,attrib,close_write,move,create,delete whatday.cpp input.txt
  ./autotest
  echo -e "------------------------------------------------------------------------$(date +%H%M%S)\n"

done
