#!/bin/bash
make FILE=$1
if [ $? -eq 0 ]
then
  cat input.txt | ./a.out > output.txt 2> error.log
  cat output.txt | xsel -ib
  cat output.txt
  cat error.log
else
  echo "Compilation error, exit."
fi
